<script setup lang="ts">
import { computed } from "vue";
import { onMounted, onUnmounted, ref } from "vue";

import OpponentLineupInput from "./OpponentLineupInput.vue";

import { getPlayersForSlot } from "../opponentSlotGender";
import { SCHEDULE_SLOT_TEMPLATE } from "../schedule";
import type {
	LineupLabMode,
	LineupRecommendationPayload,
	OpponentAssignmentsBySlot,
	OpponentRosterPlayer,
} from "../types";

interface ScheduleConfigurationBoardProps {
	mode: LineupLabMode;
	recommendationResult: LineupRecommendationPayload | null;
	opponentRosterPlayers: OpponentRosterPlayer[];
	opponentAssignments: OpponentAssignmentsBySlot;
}

const props = defineProps<ScheduleConfigurationBoardProps>();

const emit = defineEmits<{
	"update-opponent-slot": [
		roundNumber: number,
		slotNumber: number,
		playerAId: string | null,
		playerBId: string | null,
	];
}>();

const onOpponentSlotUpdate = (
	roundNumber: number,
	slotNumber: number,
	playerAId: string | null,
	playerBId: string | null,
) => {
	emit("update-opponent-slot", roundNumber, slotNumber, playerAId, playerBId);
};

const topRecommendation = computed(
	() => props.recommendationResult?.recommendations?.[0] ?? null,
);

const toPlayerName = (playerId: string): string =>
	props.recommendationResult?.playerDirectory?.[playerId] ?? playerId;

const formatWin = (value: number): string => `${Math.round(value * 100)}%`;

const openGameInfoKey = ref<string | null>(null);

const toSlotKey = (roundNumber: number, slotNumber: number): string =>
	`${roundNumber}:${slotNumber}`;

const toggleGameInfo = (roundNumber: number, slotNumber: number) => {
	const key = toSlotKey(roundNumber, slotNumber);
	openGameInfoKey.value = openGameInfoKey.value === key ? null : key;
};

const closeInfoIfOutside = (event: MouseEvent) => {
	const target = event.target as HTMLElement | null;
	if (!target?.closest("[data-game-info]")) {
		openGameInfoKey.value = null;
	}
};

const closeInfoOnEscape = (event: KeyboardEvent) => {
	if (event.key === "Escape") {
		openGameInfoKey.value = null;
	}
};

onMounted(() => {
	document.addEventListener("click", closeInfoIfOutside);
	document.addEventListener("keydown", closeInfoOnEscape);
});

onUnmounted(() => {
	document.removeEventListener("click", closeInfoIfOutside);
	document.removeEventListener("keydown", closeInfoOnEscape);
});

const getOpponentAssignment = (roundNumber: number, slotNumber: number) =>
	props.opponentAssignments[`${roundNumber}:${slotNumber}`] ?? {
		playerAId: null,
		playerBId: null,
	};

const getOutputGame = (roundNumber: number, slotNumber: number) =>
	topRecommendation.value?.rounds
		?.find((round) => round.roundNumber === roundNumber)
		?.games.find((game) => game.slotNumber === slotNumber) ?? null;

const getGameWinInfo = (roundNumber: number, slotNumber: number): string => {
	const game = getOutputGame(roundNumber, slotNumber);
	if (!game) {
		return "Win % is the predicted probability of winning this slot based on the available lineup model signals.";
	}
	return "Win % is the predicted chance this pair wins this slot. It blends baseline pair matchup rates, point-differential signal, team-strength adjustment, and DUPR blending when full four-player DUPR coverage exists. This slot adjustment signals: DUPR, Team strength.";
};

const getPlayersForSlotAt = (
	roundNumber: number,
	slotNumber: number,
	matchType: "mixed" | "female" | "male",
) => {
	const assignment = getOpponentAssignment(roundNumber, slotNumber);
	return getPlayersForSlot(
		matchType,
		props.opponentRosterPlayers,
		assignment.playerAId,
		assignment.playerBId,
	);
};
</script>

<template>
  <section class="space-y-3 rounded-lg border p-3">
    <header class="flex flex-wrap items-center justify-between gap-2 border-b pb-2">
      <h2 class="text-xs font-semibold uppercase tracking-[0.2em]">Schedule Configuration (8 Rounds)</h2>
      <p class="text-[10px] uppercase tracking-[0.14em] text-[var(--chat-muted)]">
        Generated by optimizer
      </p>
    </header>

    <p
      v-if="!topRecommendation"
      data-testid="optimizer-output-empty-state"
      class="rounded-md border px-3 py-2 text-xs text-[var(--chat-muted)]"
    >
      No generated lineup yet.
    </p>

    <article
      v-for="(roundSlots, roundIndex) in SCHEDULE_SLOT_TEMPLATE"
      :key="`round-${roundIndex + 1}`"
      :data-testid="`round-card-${roundIndex + 1}`"
      class="space-y-2 rounded-md border p-3"
    >
      <h3 class="text-xs font-semibold uppercase tracking-[0.16em]">
        R{{ roundIndex + 1 }} {{ roundSlots[0] === 'mixed' ? 'Mixed Doubles' : 'Gender Doubles' }}
      </h3>

      <div
        v-for="(matchType, slotIndex) in roundSlots"
        :key="`slot-${roundIndex + 1}-${slotIndex + 1}`"
        class="grid grid-cols-1 gap-2 md:grid-cols-2"
      >
        <OpponentLineupInput
          v-if="props.mode === 'known_opponent'"
          :round-number="roundIndex + 1"
          :slot-number="slotIndex + 1"
          :match-type="matchType"
          :players-for-a="getPlayersForSlotAt(roundIndex + 1, slotIndex + 1, matchType).playersForA"
          :players-for-b="getPlayersForSlotAt(roundIndex + 1, slotIndex + 1, matchType).playersForB"
          :player-a-id="getOpponentAssignment(roundIndex + 1, slotIndex + 1).playerAId"
          :player-b-id="getOpponentAssignment(roundIndex + 1, slotIndex + 1).playerBId"
          :empty-message-for-a="getPlayersForSlotAt(roundIndex + 1, slotIndex + 1, matchType).emptyMessageForA"
          :empty-message-for-b="getPlayersForSlotAt(roundIndex + 1, slotIndex + 1, matchType).emptyMessageForB"
          @update="onOpponentSlotUpdate"
        />
        <div
          v-else
          class="rounded-md border border-dashed px-3 py-4 text-xs text-[var(--chat-muted)]"
        >
          Hidden in Blind Mode
        </div>

        <div
          :data-testid="`round-slot-${roundIndex + 1}-${slotIndex + 1}-optimizer-output`"
          class="rounded-md border px-3 py-3 text-xs"
        >
          <p class="mb-1 uppercase tracking-[0.12em] text-[var(--chat-muted)]">{{ matchType }}</p>
          <template v-if="getOutputGame(roundIndex + 1, slotIndex + 1)">
            <p class="font-semibold">
              {{ toPlayerName(getOutputGame(roundIndex + 1, slotIndex + 1)?.playerAId ?? '') }} /
              {{ toPlayerName(getOutputGame(roundIndex + 1, slotIndex + 1)?.playerBId ?? '') }}
            </p>
            <p class="flex items-center gap-1 text-[10px] uppercase tracking-[0.12em] text-[var(--chat-muted)]">
              Win {{ formatWin(getOutputGame(roundIndex + 1, slotIndex + 1)?.winProbability ?? 0.5) }}
              <span data-game-info class="relative inline-flex">
                <button
                  type="button"
                  :data-testid="`game-win-info-button-${roundIndex + 1}-${slotIndex + 1}`"
                  class="inline-flex cursor-pointer items-center"
                  aria-label="Explain game win percentage"
                  :aria-expanded="openGameInfoKey === toSlotKey(roundIndex + 1, slotIndex + 1)"
                  @click.stop="toggleGameInfo(roundIndex + 1, slotIndex + 1)"
                >
                  <span class="inline-flex h-3.5 w-3.5 items-center justify-center rounded-full border text-[10px] font-semibold normal-case leading-none">i</span>
                </button>
                <span
                  v-if="openGameInfoKey === toSlotKey(roundIndex + 1, slotIndex + 1)"
                  :data-testid="`game-win-info-popover-${roundIndex + 1}-${slotIndex + 1}`"
                  class="absolute top-5 left-0 z-20 w-64 rounded border bg-[var(--chat-bg)] p-2 text-xs normal-case tracking-normal text-[var(--chat-text)] shadow-lg"
                >
                  {{ getGameWinInfo(roundIndex + 1, slotIndex + 1) }}
                </span>
              </span>
            </p>
          </template>
          <p v-else class="text-[var(--chat-muted)]">Pending</p>
        </div>
      </div>
    </article>
  </section>
</template>
