<script setup lang="ts">
import { computed } from "vue";

import OpponentLineupInput from "./OpponentLineupInput.vue";

import { SCHEDULE_SLOT_TEMPLATE } from "../schedule";
import type {
	LineupLabMode,
	LineupRecommendationPayload,
	OpponentAssignmentsBySlot,
	OpponentRosterPlayer,
} from "../types";

interface ScheduleConfigurationBoardProps {
	mode: LineupLabMode;
	recommendationResult: LineupRecommendationPayload | null;
	opponentRosterPlayers: OpponentRosterPlayer[];
	opponentAssignments: OpponentAssignmentsBySlot;
}

const props = defineProps<ScheduleConfigurationBoardProps>();

const emit = defineEmits<{
	"update-opponent-slot": [
		roundNumber: number,
		slotNumber: number,
		playerAId: string | null,
		playerBId: string | null,
	];
}>();

const onOpponentSlotUpdate = (
	roundNumber: number,
	slotNumber: number,
	playerAId: string | null,
	playerBId: string | null,
) => {
	emit("update-opponent-slot", roundNumber, slotNumber, playerAId, playerBId);
};

const topRecommendation = computed(
	() => props.recommendationResult?.recommendations?.[0] ?? null,
);

const toPlayerName = (playerId: string): string =>
	props.recommendationResult?.playerDirectory?.[playerId] ?? playerId;

const formatWin = (value: number): string => `${Math.round(value * 100)}%`;

const getOpponentAssignment = (roundNumber: number, slotNumber: number) =>
	props.opponentAssignments[`${roundNumber}:${slotNumber}`] ?? {
		playerAId: null,
		playerBId: null,
	};

const getOutputGame = (roundNumber: number, slotNumber: number) =>
	topRecommendation.value?.rounds
		?.find((round) => round.roundNumber === roundNumber)
		?.games.find((game) => game.slotNumber === slotNumber) ?? null;
</script>

<template>
  <section class="space-y-3 rounded-lg border p-3">
    <header class="flex flex-wrap items-center justify-between gap-2 border-b pb-2">
      <h2 class="text-xs font-semibold uppercase tracking-[0.2em]">Schedule Configuration (8 Rounds)</h2>
      <p class="text-[10px] uppercase tracking-[0.14em] text-[var(--chat-muted)]">
        Generated by optimizer
      </p>
    </header>

    <p
      v-if="!topRecommendation"
      data-testid="optimizer-output-empty-state"
      class="rounded-md border px-3 py-2 text-xs text-[var(--chat-muted)]"
    >
      No generated lineup yet.
    </p>

    <article
      v-for="(roundSlots, roundIndex) in SCHEDULE_SLOT_TEMPLATE"
      :key="`round-${roundIndex + 1}`"
      :data-testid="`round-card-${roundIndex + 1}`"
      class="space-y-2 rounded-md border p-3"
    >
      <h3 class="text-xs font-semibold uppercase tracking-[0.16em]">
        R{{ roundIndex + 1 }} {{ roundSlots[0] === 'mixed' ? 'Mixed Doubles' : 'Gender Doubles' }}
      </h3>

      <div
        v-for="(matchType, slotIndex) in roundSlots"
        :key="`slot-${roundIndex + 1}-${slotIndex + 1}`"
        class="grid grid-cols-1 gap-2 md:grid-cols-2"
      >
        <OpponentLineupInput
          v-if="props.mode === 'known_opponent'"
          :round-number="roundIndex + 1"
          :slot-number="slotIndex + 1"
          :match-type="matchType"
          :players="props.opponentRosterPlayers"
          :player-a-id="getOpponentAssignment(roundIndex + 1, slotIndex + 1).playerAId"
          :player-b-id="getOpponentAssignment(roundIndex + 1, slotIndex + 1).playerBId"
          @update="onOpponentSlotUpdate"
        />
        <div
          v-else
          class="rounded-md border border-dashed px-3 py-4 text-xs text-[var(--chat-muted)]"
        >
          Hidden in Blind Mode
        </div>

        <div
          :data-testid="`round-slot-${roundIndex + 1}-${slotIndex + 1}-optimizer-output`"
          class="rounded-md border px-3 py-3 text-xs"
        >
          <p class="mb-1 uppercase tracking-[0.12em] text-[var(--chat-muted)]">{{ matchType }}</p>
          <template v-if="getOutputGame(roundIndex + 1, slotIndex + 1)">
            <p class="font-semibold">
              {{ toPlayerName(getOutputGame(roundIndex + 1, slotIndex + 1)?.playerAId ?? '') }} /
              {{ toPlayerName(getOutputGame(roundIndex + 1, slotIndex + 1)?.playerBId ?? '') }}
            </p>
            <p class="text-[10px] uppercase tracking-[0.12em] text-[var(--chat-muted)]">
              Win {{ formatWin(getOutputGame(roundIndex + 1, slotIndex + 1)?.winProbability ?? 0.5) }}
            </p>
          </template>
          <p v-else class="text-[var(--chat-muted)]">Pending</p>
        </div>
      </div>
    </article>
  </section>
</template>
