import type { CatalogEntry } from "./catalog.types";

export const AI_CATALOG: CatalogEntry[] = [
  {
    name: "public.vw_player_team",
    description:
      "Best for identifying player roster membership by team/division/season, including gender and current-season roster flags.",
    aliases: [
      "player",
      "players",
      "team roster",
      "captain",
      "sub",
      "dupr",
      "gender",
      "current season",
    ],
    useFor: [
      "list players on a team",
      "find which team a player belongs to",
      "team roster lookup",
    ],
    avoidFor: [
      "team performance rankings",
      "match-by-match scoring details",
      "team standings leaderboard",
    ],
    exampleQuestions: [
      "What players are on Bounce Malvern 3.0",
      "List the players on Pickle Jar Green in 4.0.",
      "Which team is Brian Barenbaum on?",
    ],
    filterHints: {
      always: [
        "Filter by is_current_season = true unless a past year is mentioned.",
        "Use ILIKE for player_full_name to handle partial matches.",
      ],
      defaults: { is_current_season: "true" },
    },
    defaultSort: "is_current_season DESC, team_name ASC, player_full_name ASC",
    columns: [
      "player_full_name",
      "team_name",
      "division_name",
      "season_number",
      "season_year",
      "is_team_captain",
      "is_substitute_player",
      "dupr_rating",
      "gender",
      "is_current_season",
    ],
    sample_data: [
      {
        player_full_name: "Andrew Quinn",
        team_name: "Baltimore Pickleball Club",
        division_name: "3.5",
        season_number: 3,
        season_year: 2025,
        is_team_captain: "No",
        is_substitute_player: "No",
        gender: "Female",
        dupr_rating: null,
        is_current_season: true,
      },
      {
        player_full_name: "Barb Elgin",
        team_name: "Baltimore Pickleball Club",
        division_name: "3.5",
        season_number: 3,
        season_year: 2025,
        is_team_captain: "No",
        is_substitute_player: "No",
        gender: "Female",
        dupr_rating: null,
        is_current_season: true,
      },
    ],
  },
  {
    name: "public.vw_player_stats_per_season",
    description:
      "Best for season-level player quality and ranking questions (player performance, ranking, win rate).  Player Ranking is ordinal within the Division (1 = Best).",
    aliases: [
      "ranking",
      "rank",
      "good player",
      "bad player",
      "player performance",
      "win rate",
      "wins",
      "losses",
    ],
    useFor: [
      "evaluate how good a player is",
      "player season stats",
      "player ranking and efficiency",
      "player comparison",
    ],
    avoidFor: [
      "lineup-level game details",
      "team schedule questions",
      "team standings/pod questions",
    ],
    exampleQuestions: [
      "Is Ilene Hollin a good player?",
      "What is Brian Barenbaum's ranking?",
      "Compare two players by win rate and ranking.",
    ],
    filterHints: {
      always: [
        "Filter by is_current_season = true unless the user explicitly asks for historical seasons.",
        "Filter ranking IS NOT NULL for 'top player' queries.",
        "Filter matches_played > 0 to ensure statistical relevance.",
      ],
      onAmbiguity:
        "If no season is mentioned, use the most recent season_year and season_number.",
      defaults: { is_current_season: "true" },
    },
    defaultSort: "ranking ASC NULLS LAST",
    columns: [
      "player_full_name",
      "team_name",
      "division_name",
      "season_number",
      "season_year",
      "is_current_season",
      "dupr_rating",
      "ranking",
      "wins",
      "losses",
      "matches_played",
      "games_played",
      "win_rate",
      "points_per_game",
      "average_point_differential",
      "clutch_win_rate",
      "strength_of_opponent",
      "stats_as_of_date",
      "total_points_against",
      "total_point_differential",
      "mixed_points_per_game",
      "mixed_wins",
      "mixed_losses",
      "gender_points_per_game",
      "gender_wins",
      "gender_losses",
    ],
    sample_data: [
      {
        player_full_name: "Maria Valencia",
        team_name: "Pickle Jar",
        division_name: "3.0",
        season_number: 3,
        season_year: 2025,
        is_current_season: true,
        dupr_rating: null,
        ranking: 1,
        wins: 41,
        losses: 3,
        matches_played: 6,
        games_played: 44,
        win_rate: "93.18",
        points_per_game: "20.84",
        total_points_against: 620,
        total_point_differential: 328,
        mixed_points_per_game: "20.10",
        mixed_wins: 18,
        mixed_losses: 2,
        gender_points_per_game: "21.60",
        gender_wins: 23,
        gender_losses: 1,
        average_point_differential: "7.45",
        clutch_win_rate: "71.42",
        strength_of_opponent: "0.8623",
        stats_as_of_date: "Feb 15, 2026",
      },
      {
        player_full_name: "Uttam Purohit",
        team_name: "Monroe Flash",
        division_name: "3.0",
        season_number: 3,
        season_year: 2025,
        is_current_season: true,
        dupr_rating: null,
        ranking: 2,
        wins: 69,
        losses: 7,
        matches_played: 11,
        games_played: 76,
        win_rate: "90.78",
        points_per_game: "20.64",
        total_points_against: 1094,
        total_point_differential: 505,
        mixed_points_per_game: "19.88",
        mixed_wins: 31,
        mixed_losses: 5,
        gender_points_per_game: "21.22",
        gender_wins: 38,
        gender_losses: 2,
        average_point_differential: "6.64",
        clutch_win_rate: "63.63",
        strength_of_opponent: "1.9741",
        stats_as_of_date: "Feb 15, 2026",
      },
    ],
  },
  {
    name: "public.vw_player_stats_per_match",
    description:
      "Best for match-by-match player performance summaries within a season.",
    aliases: ["game by game", "per match", "player match stats", "week"],
    useFor: [
      "show each match a player participated in",
      "player performance by matchup",
    ],
    avoidFor: [
      "season standings leaderboards",
      "team-only schedule without player stats",
      "lineup slot details for all four players",
    ],
    exampleQuestions: [
      "Show Brian Barenbaum's match-by-match stats.",
      "How did Ilene Hollin do each week?",
      "Give me player wins/losses by matchup.",
    ],
    filterHints: {
      always: [
        "Filter by is_current_season = true unless the user explicitly asks for historical seasons.",
        "Filter by player_full_name for any individual query.",
        "Filter by is_past_match = true to exclude future scheduled matches from stats.",
        "Use match_datetime DESC to show the most recent performance first.",
      ],
      onAmbiguity:
        "If the user asks for 'recent form', filter for the last 3-5 matches by date.",
      defaults: { is_current_season: "true" },
    },
    logicBridges: [
      "This view aggregates game-level data into a single row per player per match. Use 'wins' and 'losses' columns to see their record for that specific week.",
    ],
    defaultSort:
      "season_year ASC, season_number ASC, week_number ASC, player_full_name ASC",
    columns: [
      "player_full_name",
      "team_name",
      "division_name",
      "season_number",
      "season_year",
      "is_current_season",
      "week_number",
      "match_datetime",
      "home_name",
      "away_name",
      "end_result",
      "playoffs",
      "playoff_game",
      "games_played",
      "wins",
      "losses",
      "total_points_won",
      "total_points_lost",
      "win_rate",
      "match_as_of_date",
    ],
    sample_data: [
      {
        player_full_name: "Ali Fordyce",
        team_name: "The Atlantic Club",
        division_name: "3.5 (50+)",
        season_number: 3,
        season_year: 2025,
        is_current_season: true,
        week_number: 13,
        match_datetime: "Nov 16, 2025 12:00pm",
        home_name: "The Atlantic Club",
        away_name: "Pickleball Kingdom",
        end_result: "home",
        playoffs: false,
        playoff_game: null,
        games_played: 8,
        wins: 7,
        losses: 1,
        total_points_won: 166,
        total_points_lost: 117,
        win_rate: "87.50",
        match_as_of_date: "Feb 15, 2026",
      },
      {
        player_full_name: "Anthony Ferrara",
        team_name: "Home Court",
        division_name: "3.5 (50+)",
        season_number: 3,
        season_year: 2025,
        is_current_season: true,
        week_number: 13,
        match_datetime: "Nov 16, 2025 12:00pm",
        home_name: "Stelton Sports",
        away_name: "Home Court",
        end_result: "away",
        playoffs: false,
        playoff_game: null,
        games_played: 6,
        wins: 2,
        losses: 4,
        total_points_won: 111,
        total_points_lost: 121,
        win_rate: "33.33",
        match_as_of_date: "Feb 15, 2026",
      },
    ],
  },
  {
    name: "public.vw_player_game_history",
    description:
      "Best for player-centric game history including partner and opponent pairings for each doubles game.",
    aliases: [
      "partner",
      "teammate",
      "played with",
      "play with",
      "player game history",
      "who was partner",
    ],
    useFor: [
      "who a player partnered with in a specific week or game",
      "player-by-player game outcomes and side scores",
      "opponent pair context for each player game",
    ],
    avoidFor: [
      "season standings and pod rankings",
      "season-level player ranking leaderboards",
      "team-level schedule summaries without player context",
    ],
    exampleQuestions: [
      "Who did Maria play with in week 3?",
      "Who was Brian Barenbaum's partner in week 3?",
      "Show Jeff's game-by-game partners in the North pod.",
    ],
    filterHints: {
      always: [
        "Filter by is_current_season = true unless the user explicitly asks for historical seasons.",
        "ALWAYS filter by primary_player_full_name when asking about a specific person.",
        "Matches are unpivoted; do not COUNT(*) without a player filter.",
      ],
      onAmbiguity: "Partner refers to partner_player_full_name.",
      defaults: { is_current_season: "true" },
    },
    logicBridges: [
      "Each game appears twice: once for the 'primary' player and once for their 'partner'. This allows direct filtering on any player name.",
    ],
    defaultSort: "match_datetime DESC, game_number ASC",
    columns: [
      "division_name",
      "season_number",
      "season_year",
      "is_current_season",
      "week_number",
      "match_datetime",
      "game_number",
      "match_type",
      "side",
      "primary_player_full_name",
      "partner_player_full_name",
      "opponent_player_1_full_name",
      "opponent_player_2_full_name",
      "primary_team_name",
      "opponent_team_name",
      "primary_side_score",
      "opponent_side_score",
      "game_result",
      "game_as_of_date",
    ],
    sample_data: [
      {
        division_name: "3.5 (50+)",
        season_number: 3,
        season_year: 2025,
        is_current_season: true,
        week_number: 13,
        match_datetime: "Nov 16, 2025 09:30am",
        game_number: 1,
        match_type: "mixed",
        side: "away",
        primary_player_full_name: "Christine Cardinal",
        partner_player_full_name: "Biswajit  Datta",
        opponent_player_1_full_name: "Fran Kelly",
        opponent_player_2_full_name: "Thomas Kang",
        primary_team_name: "Pickle House",
        opponent_team_name: "Bounce Malvern",
        primary_side_score: 19,
        opponent_side_score: 21,
        game_result: "loss",
        game_as_of_date: "Feb 15, 2026",
      },
      {
        division_name: "3.5 (50+)",
        season_number: 3,
        season_year: 2025,
        is_current_season: true,
        week_number: 13,
        match_datetime: "Nov 16, 2025 09:30am",
        game_number: 1,
        match_type: "mixed",
        side: "home",
        primary_player_full_name: "Fran Kelly",
        partner_player_full_name: "Thomas Kang",
        opponent_player_1_full_name: "Christine Cardinal",
        opponent_player_2_full_name: "Biswajit  Datta",
        primary_team_name: "Bounce Malvern",
        opponent_team_name: "Pickle House",
        primary_side_score: 21,
        opponent_side_score: 19,
        game_result: "win",
        game_as_of_date: "Feb 15, 2026",
      },
    ],
  },
  {
    name: "public.vw_match_game_lineups_scores",
    description:
      "Best for true match game details: home/away pairings and line-level scores.",
    aliases: [
      "lineup",
      "court",
      "game score",
      "who played",
      "boxscore",
      "score card",
      "scorecard",
    ],
    useFor: [
      "show all four players in a doubles game",
      "match lineup and score details",
    ],
    avoidFor: [
      "season-level player ranking evaluations",
      "team standings summaries",
      "high-level schedule list without lineup details",
    ],
    exampleQuestions: [
      "Who played in each game of Bounce Philly vs Bounce Malvern?",
      "Show lineup and scorecard details for week 2 Bounce Malvern vs Pickle Jar Green 4.0",
      "Give me court-by-court doubles game results.",
    ],
    filterHints: {
      always: [
        "Filter by is_current_season = true unless the user explicitly asks for historical seasons.",
        "Use this for court-level or match-level questions only.",
        "Filter by division_name to get accurate match or game details.",
        "If the user does not ask about a specific division, ask for clarification.  Do not just pick any division",
        "Search both home and away player columns if looking for a person.",
      ],
      defaults: { is_current_season: "true" },
    },
    defaultSort: "match_datetime DESC, game_number ASC",
    columns: [
      "division_name",
      "season_number",
      "season_year",
      "is_current_season",
      "week_number",
      "match_datetime",
      "home_team_name",
      "away_team_name",
      "game_number",
      "match_type",
      "home_player_1_full_name",
      "home_player_2_full_name",
      "away_player_1_full_name",
      "away_player_2_full_name",
      "home_score",
      "away_score",
      "game_winner",
      "game_as_of_date",
    ],
    sample_data: [
      {
        division_name: "3.5 (50+)",
        season_number: 3,
        season_year: 2025,
        is_current_season: true,
        week_number: 13,
        match_datetime: "Nov 16, 2025 09:30am",
        home_team_name: "Bounce Malvern",
        away_team_name: "Pickle House",
        game_number: 1,
        match_type: "mixed",
        home_player_1_full_name: "Fran Kelly",
        home_player_2_full_name: "Thomas Kang",
        away_player_1_full_name: "Christine Cardinal",
        away_player_2_full_name: "Biswajit  Datta",
        home_score: 21,
        away_score: 19,
        game_winner: "home",
        game_as_of_date: "Feb 15, 2026",
      },
      {
        division_name: "3.5 (50+)",
        season_number: 3,
        season_year: 2025,
        is_current_season: true,
        week_number: 13,
        match_datetime: "Nov 16, 2025 09:30am",
        home_team_name: "Bounce Malvern",
        away_team_name: "Pickle House",
        game_number: 2,
        match_type: "mixed",
        home_player_1_full_name: "Linda Goss",
        home_player_2_full_name: "Tim Phelan",
        away_player_1_full_name: "Quenna Walicky",
        away_player_2_full_name: "Franky Coriano",
        home_score: 24,
        away_score: 22,
        game_winner: "home",
        game_as_of_date: "Feb 15, 2026",
      },
    ],
  },
  {
    name: "public.vw_team_standings",
    description:
      "Best for team standings, rankings, pods, and season leaderboard stats.",
    aliases: ["standings", "rank", "pod", "record", "leaderboard"],
    useFor: [
      "team rank in division",
      "standings and pod ranking",
      "team season performance summary",
    ],
    avoidFor: [
      "player-specific matchup details",
      "lineup/court game detail questions",
      "single-team schedule date lookups",
      "player ranking",
    ],
    exampleQuestions: [
      "What is Bounce Philly's ranking?",
      "Show standings for division 4.0.",
      "Who leads the pod this season?",
    ],
    filterHints: {
      always: [
        "Filter by is_current_season = true unless the user explicitly asks for historical seasons.",
        "Filter by division_name to get accurate relative rankings.",
        "If the user does not ask about a specific division, ask for clarification.  Do not just pick any division",
        "Order by ranking ASC.",
      ],
      defaults: { is_current_season: "true" },
    },
    defaultSort: "division_name ASC, ranking ASC",
    columns: [
      "division_name",
      "season_number",
      "season_year",
      "is_current_season",
      "team_name",
      "ranking",
      "pod_name",
      "pod_ranking",
      "wins",
      "losses",
      "draws",
      "record",
      "game_record",
      "win_percentage",
      "game_win_rate",
      "average_points_per_game",
      "average_point_differential",
      "standings_as_of_date",
    ],
    sample_data: [
      {
        division_name: "3.0",
        season_number: 3,
        season_year: 2025,
        is_current_season: true,
        team_name: "Pickle Jar",
        ranking: 1,
        pod_name: "Northwest",
        pod_ranking: 1,
        wins: 12,
        losses: 1,
        draws: 0,
        record: "12-1-0",
        game_record: "277-139",
        win_percentage: "92.31",
        game_win_rate: "66.59",
        average_points_per_game: "634.15",
        average_point_differential: "88.15",
        standings_as_of_date: "Feb 15, 2026",
      },
      {
        division_name: "3.0",
        season_number: 3,
        season_year: 2025,
        is_current_season: true,
        team_name: "Monroe Flash",
        ranking: 2,
        pod_name: "Southwest",
        pod_ranking: 1,
        wins: 10,
        losses: 1,
        draws: 0,
        record: "10-1-0",
        game_record: "231-121",
        win_percentage: "90.91",
        game_win_rate: "65.62",
        average_points_per_game: "631.09",
        average_point_differential: "70.55",
        standings_as_of_date: "Feb 15, 2026",
      },
    ],
  },
  {
    name: "public.vw_team_matches",
    description:
      "Best for team schedule and team-level match outcomes in a single view (one row per team per matchup), including win/loss/draw and past-match flag.",
    aliases: [
      "schedule",
      "match summary",
      "team matches",
      "won or lost",
      "win loss",
      "match result",
      "every match",
      "team results",
      "upcoming",
      "calendar",
    ],
    useFor: [
      "who a team plays and when",
      "list every match for a team and result",
      "team match-by-match outcomes by week",
      "team points for and against per matchup",
    ],
    avoidFor: [
      "player-level matchup stats",
      "lineup/court-level scorecard details",
      "standings leaderboard summaries",
    ],
    exampleQuestions: [
      "Can you give me every match for Bounce Philly 4.0 and whether they won or lost?",
      "Show match-by-match results for Bounce Malvern 3.5 this season.",
      "List team outcomes by week with opponent and score.",
    ],
    filterHints: {
      always: [
        "Filter by is_current_season = true unless the user explicitly asks for historical seasons.",
        "Use is_past_match = true for results and false for schedules.",
        "Filter by team_name for specific team calendars.",
        "Filter by division_name to get accurate relative rankings.",
        "If the user does not ask about a specific division, ask for clarification.  Do not just pick any division",
      ],
      defaults: { is_current_season: "true" },
    },
    defaultSort: "match_datetime ASC",
    columns: [
      "team_name",
      "opponent_team_name",
      "division_name",
      "season_number",
      "season_year",
      "is_current_season",
      "week_number",
      "match_date",
      "match_datetime",
      "team_points",
      "opponent_points",
      "match_result",
      "playoffs",
      "playoff_game",
      "is_past_match",
    ],
    sample_data: [
      {
        team_name: "Home Court",
        opponent_team_name: "Stelton Sports",
        division_name: "3.5 (50+)",
        season_number: 3,
        season_year: 2025,
        is_current_season: true,
        week_number: 14,
        match_date: "Nov 23, 2025 12:00pm",
        match_datetime: "Nov 23, 2025 12:00pm",
        team_points: null,
        opponent_points: null,
        match_result: null,
        playoffs: false,
        playoff_game: null,
        is_past_match: false,
      },
      {
        team_name: "Bounce Malvern",
        opponent_team_name: "Pickle House",
        division_name: "3.5 (50+)",
        season_number: 3,
        season_year: 2025,
        is_current_season: true,
        week_number: 13,
        match_date: "Nov 16, 2025 09:30am",
        match_datetime: "Nov 16, 2025 09:30am",
        team_points: 633,
        opponent_points: 616,
        match_result: "Win",
        playoffs: false,
        playoff_game: null,
        is_past_match: true,
      },
    ],
  },
];
